# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph_data.proto',
  package='graph_proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10graph_data.proto\x12\x0bgraph_proto\"5\n\x05Nodes\x12\x0b\n\x03row\x18\x01 \x03(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x03(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x03(\x01\"\x85\x01\n\x05\x45\x64ges\x12\x0b\n\x03row\x18\x01 \x03(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x03(\x05\x12*\n\x05types\x18\x03 \x03(\x0e\x32\x1b.graph_proto.Edges.EdgeType\"3\n\x08\x45\x64geType\x12\x07\n\x03\x43\x46G\x10\x00\x12\x06\n\x02\x44\x44\x10\x01\x12\x06\n\x02\x43\x44\x10\x02\x12\x05\n\x01S\x10\x03\x12\x07\n\x03UNK\x10\x04\"\xde\x01\n\x07SVGraph\x12!\n\x05nodes\x18\x01 \x01(\x0b\x32\x12.graph_proto.Nodes\x12!\n\x05\x65\x64ges\x18\x02 \x01(\x0b\x32\x12.graph_proto.Edges\x12/\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x1d.graph_proto.SVGraph.Category\x12\x13\n\x0bpreferences\x18\x04 \x03(\x02\"G\n\x08\x43\x61tegory\x12\x10\n\x0creachability\x10\x00\x12\x0f\n\x0btermination\x10\x01\x12\n\n\x06memory\x10\x02\x12\x0c\n\x08overflow\x10\x03\"R\n\x07\x44\x61taset\x12#\n\x05train\x18\x01 \x03(\x0b\x32\x14.graph_proto.SVGraph\x12\"\n\x04test\x18\x02 \x03(\x0b\x32\x14.graph_proto.SVGraphb\x06proto3')
)



_EDGES_EDGETYPE = _descriptor.EnumDescriptor(
  name='EdgeType',
  full_name='graph_proto.Edges.EdgeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CFG', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNK', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=171,
  serialized_end=222,
)
_sym_db.RegisterEnumDescriptor(_EDGES_EDGETYPE)

_SVGRAPH_CATEGORY = _descriptor.EnumDescriptor(
  name='Category',
  full_name='graph_proto.SVGraph.Category',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='reachability', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='termination', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='memory', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='overflow', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=376,
  serialized_end=447,
)
_sym_db.RegisterEnumDescriptor(_SVGRAPH_CATEGORY)


_NODES = _descriptor.Descriptor(
  name='Nodes',
  full_name='graph_proto.Nodes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='graph_proto.Nodes.row', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column', full_name='graph_proto.Nodes.column', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='graph_proto.Nodes.content', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=86,
)


_EDGES = _descriptor.Descriptor(
  name='Edges',
  full_name='graph_proto.Edges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='graph_proto.Edges.row', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column', full_name='graph_proto.Edges.column', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='types', full_name='graph_proto.Edges.types', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EDGES_EDGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=222,
)


_SVGRAPH = _descriptor.Descriptor(
  name='SVGraph',
  full_name='graph_proto.SVGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='graph_proto.SVGraph.nodes', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges', full_name='graph_proto.SVGraph.edges', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='graph_proto.SVGraph.category', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preferences', full_name='graph_proto.SVGraph.preferences', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SVGRAPH_CATEGORY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=447,
)


_DATASET = _descriptor.Descriptor(
  name='Dataset',
  full_name='graph_proto.Dataset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train', full_name='graph_proto.Dataset.train', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test', full_name='graph_proto.Dataset.test', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=531,
)

_EDGES.fields_by_name['types'].enum_type = _EDGES_EDGETYPE
_EDGES_EDGETYPE.containing_type = _EDGES
_SVGRAPH.fields_by_name['nodes'].message_type = _NODES
_SVGRAPH.fields_by_name['edges'].message_type = _EDGES
_SVGRAPH.fields_by_name['category'].enum_type = _SVGRAPH_CATEGORY
_SVGRAPH_CATEGORY.containing_type = _SVGRAPH
_DATASET.fields_by_name['train'].message_type = _SVGRAPH
_DATASET.fields_by_name['test'].message_type = _SVGRAPH
DESCRIPTOR.message_types_by_name['Nodes'] = _NODES
DESCRIPTOR.message_types_by_name['Edges'] = _EDGES
DESCRIPTOR.message_types_by_name['SVGraph'] = _SVGRAPH
DESCRIPTOR.message_types_by_name['Dataset'] = _DATASET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nodes = _reflection.GeneratedProtocolMessageType('Nodes', (_message.Message,), dict(
  DESCRIPTOR = _NODES,
  __module__ = 'graph_data_pb2'
  # @@protoc_insertion_point(class_scope:graph_proto.Nodes)
  ))
_sym_db.RegisterMessage(Nodes)

Edges = _reflection.GeneratedProtocolMessageType('Edges', (_message.Message,), dict(
  DESCRIPTOR = _EDGES,
  __module__ = 'graph_data_pb2'
  # @@protoc_insertion_point(class_scope:graph_proto.Edges)
  ))
_sym_db.RegisterMessage(Edges)

SVGraph = _reflection.GeneratedProtocolMessageType('SVGraph', (_message.Message,), dict(
  DESCRIPTOR = _SVGRAPH,
  __module__ = 'graph_data_pb2'
  # @@protoc_insertion_point(class_scope:graph_proto.SVGraph)
  ))
_sym_db.RegisterMessage(SVGraph)

Dataset = _reflection.GeneratedProtocolMessageType('Dataset', (_message.Message,), dict(
  DESCRIPTOR = _DATASET,
  __module__ = 'graph_data_pb2'
  # @@protoc_insertion_point(class_scope:graph_proto.Dataset)
  ))
_sym_db.RegisterMessage(Dataset)


# @@protoc_insertion_point(module_scope)
