# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_MachineLearninForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(966, 759)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(965, 0))
        Form.setMaximumSize(QtCore.QSize(966, 16777215))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.graphWidget = PlotWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.graphWidget.setAcceptDrops(False)
        self.graphWidget.setObjectName("graphWidget")
        self.gridLayout.addWidget(self.graphWidget, 9, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.initialPopulationNumber = QtWidgets.QSpinBox(self.groupBox)
        self.initialPopulationNumber.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.initialPopulationNumber.setFont(font)
        self.initialPopulationNumber.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.initialPopulationNumber.setProperty("value", 40)
        self.initialPopulationNumber.setObjectName("initialPopulationNumber")
        self.horizontalLayout.addWidget(self.initialPopulationNumber)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.theta = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.theta.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.theta.setFont(font)
        self.theta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.theta.setDecimals(2)
        self.theta.setMaximum(1.0)
        self.theta.setSingleStep(0.1)
        self.theta.setProperty("value", 0.3)
        self.theta.setObjectName("theta")
        self.horizontalLayout_3.addWidget(self.theta)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.beta = QtWidgets.QSpinBox(self.groupBox)
        self.beta.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.beta.setFont(font)
        self.beta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.beta.setProperty("value", 5)
        self.beta.setObjectName("beta")
        self.horizontalLayout_4.addWidget(self.beta)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.generateInitialPopulationButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.generateInitialPopulationButton.setFont(font)
        self.generateInitialPopulationButton.setObjectName("generateInitialPopulationButton")
        self.verticalLayout.addWidget(self.generateInitialPopulationButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.runButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_6.addWidget(self.runButton)
        self.newProcessButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.newProcessButton.setFont(font)
        self.newProcessButton.setObjectName("newProcessButton")
        self.horizontalLayout_6.addWidget(self.newProcessButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.n = QtWidgets.QSpinBox(self.groupBox)
        self.n.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.n.setFont(font)
        self.n.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.n.setProperty("value", 20)
        self.n.setObjectName("n")
        self.horizontalLayout_2.addWidget(self.n)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.iterationNumber = QtWidgets.QSpinBox(self.groupBox)
        self.iterationNumber.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.iterationNumber.setFont(font)
        self.iterationNumber.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.iterationNumber.setMaximum(500)
        self.iterationNumber.setProperty("value", 100)
        self.iterationNumber.setObjectName("iterationNumber")
        self.horizontalLayout_5.addWidget(self.iterationNumber)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.tableView = QtWidgets.QTableView(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(375, 0))
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_7.addWidget(self.tableView)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.initialPopulationNumber, self.n)
        Form.setTabOrder(self.n, self.theta)
        Form.setTabOrder(self.theta, self.beta)
        Form.setTabOrder(self.beta, self.iterationNumber)
        Form.setTabOrder(self.iterationNumber, self.generateInitialPopulationButton)
        Form.setTabOrder(self.generateInitialPopulationButton, self.runButton)
        Form.setTabOrder(self.runButton, self.newProcessButton)
        Form.setTabOrder(self.newProcessButton, self.tableView)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Optimization Parameters"))
        self.label.setText(_translate("Form", "Initial Population Number____"))
        self.label_3.setText(_translate("Form", "Theta (ɵ)____________________"))
        self.label_4.setText(_translate("Form", "Beta (ß)_____________________"))
        self.generateInitialPopulationButton.setText(_translate("Form", "Generate Initial Population"))
        self.runButton.setText(_translate("Form", "► Run"))
        self.newProcessButton.setText(_translate("Form", "New Process"))
        self.label_2.setText(_translate("Form", "n____________________________"))
        self.label_5.setText(_translate("Form", "Iteration Number_____________"))

from pyqtgraph import PlotWidget
